### ISSUE TITLE
Value of a state machine or flow diagram

### ISSUE THREAD

**Issue by DazWilkin** [grailbio/bigmachine#14]
**Please only consider this if you've received interest from others (and they support this). I'm mostly undertaking this as a pet project and don't wish to unduly burden you for my sake.**

I've been away for 10 days and, returning to bigmachine, I'm having to rely upon extensive debugging statements in an ongoing attempt to try to grok the underlying mechanism of the solution. I still only have an admittedly loose grasp of this and am fumbling through.

The GCE implementation is able to create remote (containerized) nodes and, I believe, basic (HTTP non-TLS) RPC is working. I'm challenged debugging (particularly go routines) and because I don't have a good overall perspective.

Is|Are there (a) state diagram(s) for bigmachine? I think there are 2-3 different diagrams that are of interest:

1. The internal state diagram of an individual machine
1. The networking state diagram for the process by which the local node drives the remotes

**Comment by mariusae** [comment]
I made a first stab at this. Please let me know if it makes sense:

https://github.com/grailbio/bigmachine/blob/master/docs/impl.md

**Comment by DazWilkin** [comment]
How awesome are you?

Thank you. I'll check it out.

I'm headed out of town tomorrow for a long weekend but will be back Tuesday.

I have a GCE implementation (basically) working as of this afternoon.
