### ISSUE TITLE
Include GUID in machine addresses

### ISSUE THREAD

**Issue by mariusae** [grailbio/bigmachine#15]
Currently Bigmachine machines are named an opaque "Addr". These are https urls, e.g., `https://ec2-.../`. Addrs however do not necessarily uniquely correspond to a logical machine. In systems like AWS EC2, DNS names may be recycled, and thus Addrs need not be stable. The solution to this can be fairly simple: just suffix the URL with some sort of GUID, e.g., `https://ec2-.../unique-id`. We should think about whether we want this unique id to have other properties as well.

**Comment by DazWilkin** [comment]
In the Compute Engine and Kubernetes implementations I've prototyped, bigmachines are access remote (i.e. off-cloud, off-cluster) and only assigned IPs. I'm not using internal DNS names. As a result, when looking up bigmachines, my only key is the IP and I must reverse these back into some e.g. Compute Engine identifier or Kubernetes service name. IPs are, of course unique, and so this mapping is one:one but, it's inconvenient. I could add a key-value store to `System` and retain this mapping `map[ip]instance` but, it feels it would be easier for the `bigmachine.Machine` type to have a unique (user-defined) identifier too. Better yet an interface. Thoughts?

**Comment by mariusae** [comment]
The issue identified here is that ip addresses/DNS names/etc can be recycled, and thus make for poor identifiers. I think the solution is straightforward: since addresses are anyway a URL, we can add some sort of unique path prefix every time a machine boots up. (It could even just be a timestamp.)

I don't really see an issue in using URLs directly as identifiers. They are quite convenient: they carry information that can be used during debugging (e.g., the IPs/DNS names could be looked up in the cloud provider's console), and they already have a canonical string representation..
