### ISSUE TITLE
Consider SemVer for releases

### ISSUE THREAD

**Issue by DazWilkin** [grailbio/bigmachine#5]
The initial release [`v0.5`](https://github.com/grailbio/bigmachine/tree/v0.5) does not use SemVer and -- IIUC -- this is problematic for Go Modules:

```
go get github.com/grailbio/bigmachine@v0.5
go get github.com/grailbio/bigmachine@v0.5: no matching versions for query "v0.5"
```
Whereas getting it by its commit, works:
```
go get github.com/grailbio/bigmachine@6ab40c5aa9bcc7030513289106a2fa20697ed731
go: finding github.com/grailbio/bigmachine 6ab40c5aa9bcc7030513289106a2fa20697ed731
```
and:
```
go list -f "{{ .Dir }}" -m github.com/grailbio/bigmachine
${GOPATH}/pkg/mod/github.com/grailbio/bigmachine@v0.0.0-20191001220847-6ab40c5aa9bc
```

**Comment by mariusae** [comment]
This was the intent; I guess I naively assumed that if you left out the patch version it sorted before patch `.0`.

**Comment by mariusae** [comment]
I've created a new release: https://github.com/grailbio/bigmachine/releases/tag/v0.5.0
